var adaptationRules = [
    {
        "name":"nightMode",
        "enabled":true,
        "active":false,
        "condition":
            {
                "operator":">",
                "operant1":"time",
                "operant2":"20"
            },
        "action":"nightMode"
    },
    {
        "name":"highAmbientLight",
        "enabled":true,
        "active":false,
        "condition":
            {
                "operator":">=",
                "operant1":"light",
                "operant2":"50"
            },
        "action":"highAmbientLight"
    },
    {
        "name":"lowAmbientLight",
        "enabled":true,
        "active":false,
        "condition":
            {
                "operator":"<=",
                "operant1":"light",
                "operant2":"10"
            },
        "action":"lowAmbientLight"
    },
    {
        "name":"greaterFontSize",
        "enabled":true,
        "active":false,
        "condition":
            {
                "operator":">",
                "operant1":"age",
                "operant2":"50"
            },
        "action":"greaterFontSize"
    },
    {
        "name":"custom",
        "enabled":true,
        "active":false,
        "condition":
            {
                "operator":"<",
                "operant1":"light",
                "operant2":"50"
            },
        "action":"customOperation"
    },
    {
        "name":"blackWhiteMode",
        "enabled":true,
        "active":false,
        "condition":
            {
                "operator":"<",
                "operant1":"light",
                "operant2":"50"
            },
        "action":"blackWhiteMode"
    },
    {
        "name":"modalityChange",
        "enabled":true,
        "active":false,
        "condition":
            {
                "operator":">=",
                "operant1":"activity",
                "operant2":"1"
            },
        "action":"modalityChange"
    },
    {
        "name":"navGrid",
        "enabled":true,
        "active":false,
        "condition":
            {
                "operator":">=",
                "operant1":"activity",
                "operant2":"1"
            },
        "action":"navGrid"
    }
  ];